import React from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/landing/Footer";

export default function TermsOfService() {
  return (
    <div className="flex flex-col min-h-screen relative overflow-hidden bg-gradient-to-br from-green-50 via-white to-green-50/50">
      <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] rounded-full bg-green-200/40 mix-blend-multiply blur-[120px] pointer-events-none" />
      <div className="absolute top-[20%] right-[-5%] w-[30%] h-[40%] rounded-full bg-emerald-200/30 mix-blend-multiply blur-[120px] pointer-events-none" />
      <div className="absolute bottom-[-10%] left-[20%] w-[50%] h-[40%] rounded-full bg-teal-100/40 mix-blend-multiply blur-[120px] pointer-events-none" />

      <div className="relative z-10 flex flex-col min-h-screen">
        <Navbar />
        <main className="flex-grow py-32 px-6 lg:px-8 max-w-4xl mx-auto w-full">
          <div className="bg-white/60 backdrop-blur-xl border border-white/50 rounded-3xl p-10 md:p-16 shadow-[0_8px_32px_rgba(34,197,94,0.05)]">
            <h1 className="text-4xl font-extrabold text-slate-900 mb-8">Terms of Service</h1>
            <div className="prose prose-slate max-w-none text-slate-600 font-medium space-y-6">
              <p>Last Updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
              
              <h2 className="text-2xl font-bold text-slate-900 mt-10 mb-4">1. Acceptance of Terms</h2>
              <p>
                By accessing or using the HireNP platform, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the service.
              </p>

              <h2 className="text-2xl font-bold text-slate-900 mt-10 mb-4">2. Description of Service</h2>
              <p>
                HireNP provides an automated hiring system, including AI-powered candidate evaluation, interview scheduling, and associated communication tools. We reserve the right to modify or discontinue, temporarily or permanently, the service with or without notice.
              </p>

              <h2 className="text-2xl font-bold text-slate-900 mt-10 mb-4">3. User Responsibilities</h2>
              <p>
                You are responsible for maintaining the confidentiality of your account and password. You agree to use the platform in compliance with all applicable local, state, national, and international laws, rules, and regulations, particularly regarding employment practices and candidate privacy.
              </p>

              <h2 className="text-2xl font-bold text-slate-900 mt-10 mb-4">4. AI Insights and Decisions</h2>
              <p>
                HireNP uses artificial intelligence to assist in evaluating candidates. While our AI aims to provide accurate and helpful insights, the final hiring decisions remain entirely the responsibility of your organization. HireNP is not liable for employment decisions made based on data or summaries generated by the platform.
              </p>

              <h2 className="text-2xl font-bold text-slate-900 mt-10 mb-4">5. Intellectual Property</h2>
              <p>
                The service and its original content, features, and functionality are and will remain the exclusive property of HireNP and its licensors. The platform is protected by copyright, trademark, and other laws.
              </p>

              <h2 className="text-2xl font-bold text-slate-900 mt-10 mb-4">6. Limitation of Liability</h2>
              <p>
                In no event shall HireNP, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the service.
              </p>

              <h2 className="text-2xl font-bold text-slate-900 mt-10 mb-4">7. Contact Information</h2>
              <p>
                If you have any questions about these Terms, please contact us at support@hirenp.com.
              </p>
            </div>
          </div>
        </main>
        <Footer />
      </div>
    </div>
  );
}
