import React from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function TermsOfService() {
  return (
    <div className="flex flex-col min-h-screen bg-white">
      <Navbar />
      <main className="flex-grow">

        {/* HERO */}
        <section className="relative pt-28 pb-12 lg:pt-32 lg:pb-16 px-5 lg:px-6 overflow-hidden">
          <div className="absolute inset-0 bg-grid mask-radial opacity-60 pointer-events-none" />
          <div className="relative max-w-3xl mx-auto text-center">
            <span className="inline-flex items-center gap-1.5 text-[10px] font-semibold tracking-[0.16em] uppercase text-brand-primary mb-3">
              <span className="w-3 h-px bg-brand-primary/50" /> Legal
            </span>
            <h1 className="text-3xl md:text-5xl font-serif text-ink-900 mb-3 leading-[1.05] tracking-[-0.025em]">Terms of Service</h1>
            <p className="text-ink-400 text-[13px] font-medium">
              Last updated · {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
            </p>
          </div>
        </section>

        <section className="px-5 lg:px-6 max-w-2xl mx-auto py-12 lg:py-16">
          <div className="prose prose-base max-w-none text-ink-700 prose-headings:font-serif prose-headings:tracking-tight prose-headings:text-ink-900 prose-h2:text-xl prose-h2:mt-10 prose-h2:mb-3 prose-p:leading-relaxed prose-strong:text-ink-900 prose-a:text-brand-primary prose-a:no-underline hover:prose-a:underline">
            <h2>1. Acceptance of terms</h2>
            <p>By accessing or using the HireNP platform, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the service.</p>

            <h2>2. Description of service</h2>
            <p>HireNP provides an automated hiring system, including AI-powered candidate evaluation, interview scheduling, and associated communication tools. We reserve the right to modify or discontinue, temporarily or permanently, the service with or without notice.</p>

            <h2>3. User responsibilities</h2>
            <p>You are responsible for maintaining the confidentiality of your account and password. You agree to use the platform in compliance with all applicable local, state, national, and international laws, rules, and regulations, particularly regarding employment practices and candidate privacy.</p>

            <h2>4. AI insights and decisions</h2>
            <p>HireNP uses artificial intelligence to assist in evaluating candidates. While our AI aims to provide accurate and helpful insights, the final hiring decisions remain entirely the responsibility of your organization. HireNP is not liable for employment decisions made based on data or summaries generated by the platform.</p>

            <h2>5. Intellectual property</h2>
            <p>The service and its original content, features, and functionality are and will remain the exclusive property of HireNP and its licensors. The platform is protected by copyright, trademark, and other laws.</p>

            <h2>6. Limitation of liability</h2>
            <p>In no event shall HireNP, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the service.</p>

            <h2>7. Contact information</h2>
            <p>If you have any questions about these Terms, please contact us at <a href="mailto:support@hirenp.com">support@hirenp.com</a>.</p>
          </div>
        </section>

      </main>
      <Footer />
    </div>
  );
}
