import React from 'react';

const HIRENP_FEATURES = [
  { category: '🤖 AI & Intelligence' },
  {
    key: 'ai_resume_scoring',
    feature: 'AI Resume Scoring',
    description: 'Score every applicant instantly',
    hirenp: '✓ Deep scoring with full reasoning',
    hirenp_note: 'Scores against YOUR job requirements',
    wins: true,
    unique: false,
  },
  {
    key: 'ai_reasoning',
    feature: 'AI Reasoning Transparency',
    description: 'WHY every decision was made',
    hirenp: '✓ Every decision fully explained',
    hirenp_note: 'See exactly why candidate ranked',
    wins: true,
    unique: true,
  },
  {
    key: 'ai_job_builder',
    feature: 'AI Job Description Builder',
    description: 'Plain English → full JD in seconds',
    hirenp: '✓ Describe role, AI builds everything',
    hirenp_note: 'Requirements, scoring criteria, JD',
    wins: true,
    unique: false,
  },
  {
    key: 'emma_ai',
    feature: 'Emma AI — Hiring Assistant',
    description: 'Ask anything about your pipeline',
    hirenp: '✓ Full pipeline intelligence 24/7',
    hirenp_note: 'Daily briefing, metrics, summaries',
    wins: true,
    unique: true,
  },
  {
    key: 'ai_shortlisting',
    feature: 'AI Candidate Shortlisting',
    description: 'Auto-ranks top candidates per job',
    hirenp: '✓ Ranked with full reasoning',
    hirenp_note: 'Not just ranked — explained',
    wins: true,
    unique: false,
  },
  {
    key: 'bias_detection',
    feature: 'AI Bias Detection',
    description: 'Flags potential hiring bias',
    hirenp: '✓ Business plan',
    hirenp_note: 'Compliance-ready for enterprises',
    wins: true,
    unique: false,
  },
  {
    key: 'ai_salary',
    feature: 'AI Suggested Salary',
    description: 'Salary recommendation per candidate',
    hirenp: '✓ Based on interview performance',
    hirenp_note: 'Market-calibrated suggestion',
    wins: true,
    unique: true,
  },
  {
    key: 'requirements_gap',
    feature: 'Requirements Met vs Missing',
    description: 'Exact gap analysis per candidate',
    hirenp: '✓ Side-by-side breakdown',
    hirenp_note: 'Every gap shown, every strength shown',
    wins: true,
    unique: true,
  },
  {
    key: 'red_flags',
    feature: 'AI Red Flag Detection',
    description: 'Surfaces critical warning signs',
    hirenp: '✓ Automatic in every review',
    hirenp_note: 'Never miss a critical issue',
    wins: true,
    unique: true,
  },
  {
    key: 'daily_briefing',
    feature: 'AI Daily Hiring Briefing',
    description: 'Morning summary of pipeline',
    hirenp: '✓ Via Emma AI every morning',
    hirenp_note: 'Know your pipeline before 9am',
    wins: true,
    unique: true,
  },
  {
    key: 'candidate_research',
    feature: 'AI Candidate Research Tools',
    description: 'Deep intelligence on every candidate',
    hirenp: '✓ Full research profile',
    hirenp_note: 'Beyond resume parsing',
    wins: true,
    unique: true,
  },
  { category: '👥 Candidate Management' },
  {
    key: 'ats',
    feature: 'Applicant Tracking System',
    description: 'Full pipeline from apply to hire',
    hirenp: '✓ Complete ATS built-in',
    hirenp_note: 'No separate ATS needed',
    wins: true,
    unique: false,
  },
  {
    key: 'candidate_profile',
    feature: 'Candidate Profile Deep-Dive',
    description: 'Complete intelligence per candidate',
    hirenp: '✓ AI + manual + interview data',
    hirenp_note: 'Fullest picture of any platform',
    wins: true,
    unique: false,
  },
  {
    key: 'stage_tracking',
    feature: 'Candidate Stage Tracking',
    description: 'Applied → Analyzed → Interview → Hired',
    hirenp: '✓ Visual pipeline with AI at every step',
    hirenp_note: 'AI enriches every stage',
    wins: true,
    unique: false,
  },
  {
    key: 'bulk_actions',
    feature: 'Bulk Candidate Actions',
    description: 'Manage many candidates at once',
    hirenp: '✓ Filter + bulk advance/reject',
    hirenp_note: 'Handle 100s in minutes',
    wins: true,
    unique: false,
  },
  {
    key: 'score_threshold',
    feature: 'Per-Job Score Threshold',
    description: 'Custom quality bar per role',
    hirenp: '✓ Slider per job posting',
    hirenp_note: 'Different bar for every role',
    wins: true,
    unique: true,
  },
  {
    key: 'candidate_pool',
    feature: 'Candidate Pool',
    description: 'Searchable talent database',
    hirenp: '✓ Pro + Business plans',
    hirenp_note: 'Grows with every signup',
    wins: false,
    unique: false,
  },
  {
    key: 'pool_invites',
    feature: 'Candidate Pool Invitations',
    description: 'Invite pool candidates to apply',
    hirenp: '✓ Direct targeted invitations',
    hirenp_note: 'Candidates choose to respond',
    wins: true,
    unique: false,
  },
  {
    key: 'pool_ai_match',
    feature: 'AI Pool Matching',
    description: 'AI finds best pool candidates per job',
    hirenp: '✓ Auto-match on every job post',
    hirenp_note: 'Top 10 matches surfaced instantly',
    wins: true,
    unique: true,
  },
  { category: '🎙️ Interview Intelligence' },
  {
    key: 'ai_bot',
    feature: 'AI Interview Bot',
    description: 'AI joins and records every interview',
    hirenp: '✓ Joins Google Meet automatically',
    hirenp_note: 'Toggle on/off per interview',
    wins: true,
    unique: false,
  },
  {
    key: 'transcription',
    feature: 'Full Interview Transcription',
    description: 'Word-for-word transcript',
    hirenp: '✓ Complete transcript always saved',
    hirenp_note: 'Searchable, downloadable',
    wins: true,
    unique: false,
  },
  {
    key: 'interview_analysis',
    feature: 'Deep Interview Analysis',
    description: 'AI analyzes transcript deeply',
    hirenp: '✓ Competency-by-competency analysis',
    hirenp_note: 'Not just summary — deep scoring',
    wins: true,
    unique: false,
  },
  {
    key: 'interview_scoring',
    feature: '3-Dimensional Interview Scoring',
    description: 'Communication/Technical/Culture',
    hirenp: '✓ Three separate scored dimensions',
    hirenp_note: 'Full picture of candidate ability',
    wins: true,
    unique: true,
  },
  {
    key: 'combined_score',
    feature: 'Combined Resume + Interview Score',
    description: 'Holistic weighted candidate score',
    hirenp: '✓ Resume + Interview = Combined',
    hirenp_note: 'Weighted for fairer decisions',
    wins: true,
    unique: true,
  },
  {
    key: 'interview_strengths',
    feature: 'Interview Strengths & Growth Areas',
    description: 'Specific post-interview insights',
    hirenp: '✓ Auto-generated per interview',
    hirenp_note: 'Ready before debrief meeting',
    wins: true,
    unique: true,
  },
  {
    key: 'critical_red_flags',
    feature: 'Critical Red Flags',
    description: 'Automatic warning detection',
    hirenp: '✓ Highlighted in every report',
    hirenp_note: 'Never miss a red flag again',
    wins: true,
    unique: true,
  },
  {
    key: 'multi_step',
    feature: 'Multi-Step Interview Workflow',
    description: 'Screening → Technical → Final',
    hirenp: '✓ Unlimited custom stages',
    hirenp_note: 'Each stage scored independently',
    wins: true,
    unique: false,
  },
  {
    key: 'interview_hub',
    feature: 'Interview Hub',
    description: 'Manage all interviews centrally',
    hirenp: '✓ All interviews in one place',
    hirenp_note: 'Schedule, track, analyze',
    wins: true,
    unique: false,
  },
  {
    key: 'full_transcript',
    feature: 'View Full Transcript',
    description: 'Read complete interview transcript',
    hirenp: '✓ Always available, searchable',
    hirenp_note: 'Evidence for every decision',
    wins: true,
    unique: false,
  },
  {
    key: 'executive_summary',
    feature: 'AI Executive Interview Summary',
    description: 'One-paragraph candidate verdict',
    hirenp: '✓ Auto-generated after every interview',
    hirenp_note: 'Share with any stakeholder instantly',
    wins: true,
    unique: true,
  },
  { category: '📅 Scheduling' },
  {
    key: 'scheduling',
    feature: 'Interview Scheduling',
    description: 'Coordinate interview times',
    hirenp: '✓ Fully built-in',
    hirenp_note: 'No Calendly needed',
    wins: true,
    unique: false,
  },
  {
    key: 'natural_language',
    feature: 'Natural Language Scheduling',
    description: '"Weekdays 2-5pm" → done',
    hirenp: '✓ Plain English commands',
    hirenp_note: 'Type it like a text message',
    wins: true,
    unique: true,
  },
  {
    key: 'gcal_sync',
    feature: 'Google Calendar Sync',
    description: 'Two-way calendar integration',
    hirenp: '✓ G-Sync active indicator',
    hirenp_note: 'Always in sync',
    wins: true,
    unique: false,
  },
  {
    key: 'self_scheduling',
    feature: 'Candidate Self-Scheduling',
    description: 'Candidates pick their own slot',
    hirenp: '✓ Fully automated',
    hirenp_note: 'Zero back-and-forth emails',
    wins: true,
    unique: false,
  },
  {
    key: 'availability',
    feature: 'Availability Pool Management',
    description: 'Set recurring availability slots',
    hirenp: '✓ Slot pool with live availability',
    hirenp_note: 'Set once, reuse forever',
    wins: true,
    unique: false,
  },
  {
    key: 'double_booking',
    feature: 'Double-Booking Prevention',
    description: 'Automatic conflict detection',
    hirenp: '✓ Smart slot locking',
    hirenp_note: 'First to confirm wins',
    wins: true,
    unique: false,
  },
  {
    key: 'reschedule',
    feature: 'Reschedule Management',
    description: 'Handle reschedule requests',
    hirenp: '✓ Dashboard reschedule queue',
    hirenp_note: 'Tracked in needs-attention queue',
    wins: true,
    unique: true,
  },
  { category: '💼 Job Management' },
  {
    key: 'job_posting',
    feature: 'Job Posting Creation',
    description: 'Create and publish job listings',
    hirenp: '✓ Manual or AI-built in 2 minutes',
    hirenp_note: 'Both options always available',
    wins: true,
    unique: false,
  },
  {
    key: 'ai_job_architect',
    feature: 'AI Job Architect',
    description: 'AI builds full job from description',
    hirenp: '✓ Plain English → complete JD',
    hirenp_note: 'Requirements auto-generated',
    wins: true,
    unique: true,
  },
  {
    key: 'hiring_policy',
    feature: 'Company Hiring Policy',
    description: 'Set must-haves and deal-breakers',
    hirenp: '✓ Directly feeds AI scoring',
    hirenp_note: 'AI uses YOUR standards',
    wins: true,
    unique: true,
  },
  {
    key: 'job_threshold',
    feature: 'Per-Job Match Threshold',
    description: 'Custom quality bar per role',
    hirenp: '✓ Adjustable slider per job',
    hirenp_note: 'Senior role needs 80%+ not 60%',
    wins: true,
    unique: true,
  },
  {
    key: 'job_analytics',
    feature: 'Job Performance Panel',
    description: 'Top/Mid/Weak breakdown per job',
    hirenp: '✓ Live performance panel',
    hirenp_note: 'Instant quality overview',
    wins: true,
    unique: true,
  },
  {
    key: 'job_lifecycle',
    feature: 'Job Lifecycle Management',
    description: 'Active/Archived/Draft jobs',
    hirenp: '✓ Full lifecycle control',
    hirenp_note: 'Nothing gets lost',
    wins: true,
    unique: false,
  },
  { category: '📄 Offers & Onboarding' },
  {
    key: 'offer_generation',
    feature: 'AI Offer Letter Generation',
    description: 'Create professional offer letters',
    hirenp: '✓ AI-generated in seconds',
    hirenp_note: 'Personalized to each candidate',
    wins: true,
    unique: false,
  },
  {
    key: 'live_preview',
    feature: 'Live Offer Letter Preview',
    description: 'See letter update as you type',
    hirenp: '✓ Real-time split-screen preview',
    hirenp_note: 'What you type is what they get',
    wins: true,
    unique: true,
  },
  {
    key: 'digital_signing',
    feature: 'Digital Signing',
    description: 'Candidate signs offer digitally',
    hirenp: '✓ Built-in — no DocuSign needed',
    hirenp_note: 'Saves $25/month on DocuSign',
    wins: true,
    unique: false,
  },
  {
    key: 'ai_offer_engine',
    feature: 'AI Offer Engine',
    description: 'AI suggests terms and salary',
    hirenp: '✓ Salary suggestion from interview',
    hirenp_note: 'Data-backed offer every time',
    wins: true,
    unique: true,
  },
  {
    key: 'offer_tracking',
    feature: 'Offer Status Tracking',
    description: 'Track sent/accepted/declined',
    hirenp: '✓ Real-time status dashboard',
    hirenp_note: 'Know instantly when signed',
    wins: true,
    unique: false,
  },
  {
    key: 'onboarding',
    feature: 'Onboarding Integration',
    description: 'Smooth transition after hire',
    hirenp: '✓ Business plan',
    hirenp_note: 'Hire to onboard in one system',
    wins: true,
    unique: false,
  },
  { category: '📧 Communication' },
  {
    key: 'email_tracker',
    feature: 'Email Tracker',
    description: 'Full audit trail of all emails',
    hirenp: '✓ Every email logged with type',
    hirenp_note: 'Offer/Invite/Confirm all tracked',
    wins: true,
    unique: false,
  },
  {
    key: 'auto_emails',
    feature: 'Automated Email Sequences',
    description: 'Auto-send status updates',
    hirenp: '✓ Interview/Confirm/Offer auto-sent',
    hirenp_note: 'Candidates never left waiting',
    wins: true,
    unique: false,
  },
  {
    key: 'candidate_notifications',
    feature: 'Candidate Notifications',
    description: 'Keep candidates informed',
    hirenp: '✓ Automated at every stage',
    hirenp_note: 'Better candidate experience',
    wins: true,
    unique: false,
  },
  {
    key: 'google_meet',
    feature: 'Google Meet Integration',
    description: 'Video interviews via Google Meet',
    hirenp: '✓ Native — AI bot joins automatically',
    hirenp_note: 'No separate video tool',
    wins: true,
    unique: false,
  },
  { category: '🧑‍💼 Candidate Experience' },
  {
    key: 'candidate_dashboard',
    feature: 'Candidate Dashboard',
    description: 'Candidates track applications',
    hirenp: '✓ Full journey view',
    hirenp_note: 'Applied/Interview/Hired stages',
    wins: true,
    unique: false,
  },
  {
    key: 'career_advisor',
    feature: 'AI Career Advisor',
    description: 'AI helps candidates grow',
    hirenp: '✓ Emma gives career guidance',
    hirenp_note: 'Personalized to their profile',
    wins: true,
    unique: true,
  },
  {
    key: 'app_status',
    feature: 'Application Status Visibility',
    description: 'Candidates see where they stand',
    hirenp: '✓ Real-time stage updates',
    hirenp_note: 'No ghosting on HireNP',
    wins: true,
    unique: false,
  },
  {
    key: 'resume_vault',
    feature: 'Resume Vault',
    description: 'Store multiple resume versions',
    hirenp: '✓ Built-in vault',
    hirenp_note: 'Best version for each job',
    wins: true,
    unique: true,
  },
  {
    key: 'ai_autofill',
    feature: 'AI Profile Auto-Fill',
    description: 'AI fills profile from resume',
    hirenp: '✓ One-click from resume upload',
    hirenp_note: 'Profile complete in seconds',
    wins: true,
    unique: true,
  },
  {
    key: 'job_portal',
    feature: 'Job Search Portal',
    description: 'Browse and apply to open roles',
    hirenp: '✓ Full job board for candidates',
    hirenp_note: 'Growing job marketplace',
    wins: false,
    unique: false,
  },
  {
    key: 'job_chat_bot',
    feature: 'Per-Job AI Chat Bot',
    description: 'Ask questions about specific jobs',
    hirenp: '✓ Unique bot per job posting',
    hirenp_note: 'Candidates get instant answers',
    wins: true,
    unique: true,
  },
  { category: '📊 Analytics & Reporting' },
  {
    key: 'hiring_dashboard',
    feature: 'Hiring Intelligence Dashboard',
    description: 'Full overview of hiring activity',
    hirenp: '✓ Real-time intelligence overview',
    hirenp_note: 'Jobs/Pool/Saved/Emails/Offers',
    wins: true,
    unique: false,
  },
  {
    key: 'roi_tracking',
    feature: 'Recruitment ROI Tracking',
    description: 'Agency fees saved + hours saved',
    hirenp: '✓ Live ROI calculation',
    hirenp_note: 'Justify HireNP to any CFO',
    wins: true,
    unique: true,
  },
  {
    key: 'pipeline_funnel',
    feature: 'Pipeline Funnel Analytics',
    description: 'Conversion at every stage',
    hirenp: '✓ Visual funnel with percentages',
    hirenp_note: 'See where candidates drop off',
    wins: true,
    unique: false,
  },
  {
    key: 'time_to_hire',
    feature: 'Time-to-Hire Tracking',
    description: 'Measure hiring speed per role',
    hirenp: '✓ Per job tracking',
    hirenp_note: 'Average 11 days on HireNP',
    wins: true,
    unique: false,
  },
  {
    key: 'token_analytics',
    feature: 'AI Usage Analytics',
    description: 'Track AI feature consumption',
    hirenp: '✓ Full token usage dashboard',
    hirenp_note: 'Know exactly what AI you use',
    wins: true,
    unique: true,
  },
  { category: '⚙️ Platform & Settings' },
  {
    key: 'company_setup',
    feature: 'Complete Company Setup',
    description: 'Full company configuration',
    hirenp: '✓ Profile/Policy/Timezone/Currency',
    hirenp_note: 'Everything in one settings page',
    wins: true,
    unique: false,
  },
  {
    key: 'timezone_location',
    feature: 'Timezone + Location Settings',
    description: 'Localized platform experience',
    hirenp: '✓ Full timezone localization',
    hirenp_note: 'USA and Nepal timezones',
    wins: true,
    unique: false,
  },
  {
    key: 'team_management',
    feature: 'Team Member Management',
    description: 'Add HR team with role access',
    hirenp: '✓ Role-based permissions',
    hirenp_note: '3 members Pro / Unlimited Business',
    wins: true,
    unique: false,
  },
  {
    key: 'multi_currency',
    feature: 'Multi-Currency Support',
    description: 'USD and NPR supported',
    hirenp: '✓ USD + NPR natively',
    hirenp_note: 'Only platform with NPR support',
    wins: true,
    unique: true,
  },
  {
    key: 'nepal_compliance',
    feature: 'Nepal Labor Law Compliance',
    description: 'Compliant hiring for Nepal',
    hirenp: '✓ Business plan',
    hirenp_note: 'Only platform with this',
    wins: true,
    unique: true,
  },
  {
    key: 'white_label',
    feature: 'White Label Branding',
    description: 'Your brand on the platform',
    hirenp: '✓ Business plan',
    hirenp_note: 'Full brand customization',
    wins: true,
    unique: false,
  },
  {
    key: 'setup_checklist',
    feature: 'Guided Setup Checklist',
    description: 'Onboarding in under 10 minutes',
    hirenp: '✓ Step-by-step with % progress',
    hirenp_note: 'Up and running in minutes',
    wins: true,
    unique: false,
  },
  {
    key: 'priority_support',
    feature: 'Priority Support',
    description: 'Fast response support',
    hirenp: '✓ Business plan',
    hirenp_note: '24hr response time',
    wins: true,
    unique: false,
  },
  { category: '💰 Pricing & Access' },
  {
    key: 'free_trial',
    feature: '15-Day Free Trial',
    description: 'Full access before paying',
    hirenp: '✓ 15 days, no card required',
    hirenp_note: 'Run a real hire during trial',
    wins: true,
    unique: false,
  },
  {
    key: 'free_plan',
    feature: 'Permanent Free Plan',
    description: 'Free forever tier',
    hirenp: '✓ Always free',
    hirenp_note: '1 job, 20 candidates',
    wins: true,
    unique: false,
  },
  {
    key: 'pay_per_job',
    feature: 'Pay Per Job Option',
    description: 'Pay only for what you use',
    hirenp: '✓ $60/job — full workflow',
    hirenp_note: 'Perfect for occasional hiring',
    wins: true,
    unique: false,
  },
  {
    key: 'pay_when_hiring',
    feature: 'Pay Only When Hiring',
    description: 'Stop paying between hires',
    hirenp: '✓ 30 days, pause anytime',
    hirenp_note: 'Why pay 12 months for 4 months hiring?',
    wins: true,
    unique: true,
  },
  {
    key: 'no_annual_contract',
    feature: 'No Annual Contract',
    description: 'Month-to-month flexibility',
    hirenp: '✓ 30 days at a time',
    hirenp_note: 'Cancel anytime, no penalty',
    wins: true,
    unique: false,
  },
  {
    key: 'no_implementation_fee',
    feature: 'Zero Implementation Fee',
    description: 'No setup cost',
    hirenp: '✓ $0 to get started',
    hirenp_note: 'Greenhouse charges $2K-$10K',
    wins: true,
    unique: false,
  },
  {
    key: 'no_per_seat',
    feature: 'No Per-Seat Pricing',
    description: 'Flat price not per user',
    hirenp: '✓ Flat price per plan',
    hirenp_note: 'Add team without extra cost',
    wins: true,
    unique: false,
  },
  {
    key: 'npr_pricing',
    feature: 'NPR Pricing for Nepal',
    description: 'Local currency for Nepal',
    hirenp: '✓ 50% lower NPR pricing',
    hirenp_note: 'Pro at NPR 19,900/30 days',
    wins: true,
    unique: true,
  },
  {
    key: 'esewa_khalti',
    feature: 'eSewa + Khalti Payments',
    description: 'Nepal payment methods',
    hirenp: '✓ Both gateways supported',
    hirenp_note: 'Only hiring platform with this',
    wins: true,
    unique: true,
  },
  {
    key: 'pro_pricing',
    feature: 'Pro Plan Price',
    description: 'Main plan for most companies',
    hirenp: '✓ $299/30 days',
    hirenp_note: 'Everything included. No add-ons.',
    wins: true,
    unique: false,
  },
  {
    key: 'business_pricing',
    feature: 'Business Plan Price',
    description: 'Unlimited everything',
    hirenp: '✓ $400/30 days',
    hirenp_note: 'Only $101 more than Pro',
    wins: true,
    unique: false,
  },
  {
    key: 'cost_per_hire',
    feature: 'Cost Per Hire (5 hires/yr)',
    description: 'Real annual cost for typical team',
    hirenp: '✓ ~$600-1,196/year',
    hirenp_note: '3-4 months hiring × $299',
    wins: true,
    unique: false,
  },
  {
    key: 'vs_agency_savings',
    feature: 'Savings vs Agency (5 hires)',
    description: 'Agency charges 15-25% per hire',
    hirenp: '✓ Save $70,000-$74,000/year',
    hirenp_note: 'Agency = $75K. HireNP = $1,196.',
    wins: true,
    unique: false,
  },
];

const COMPETITOR_DATA = {
  linkedin: {
    name: 'LinkedIn Recruiter',
    tagline: '$10,000+/yr sourcing tool',
    ai_resume_scoring: 'Basic keyword',
    ai_reasoning: '✗',
    ai_job_builder: '✗',
    emma_ai: '✗',
    ai_shortlisting: 'Basic',
    bias_detection: '✗',
    ai_salary: '✗',
    requirements_gap: '✗',
    red_flags: '✗',
    daily_briefing: '✗',
    candidate_research: 'LinkedIn profile only',
    ats: 'Basic pipeline',
    candidate_profile: 'LinkedIn profile',
    stage_tracking: 'Basic',
    bulk_actions: '✓',
    score_threshold: '✗',
    candidate_pool: '✓ 900M+ profiles',
    pool_invites: '✓ InMail',
    pool_ai_match: 'Basic',
    ai_bot: '✗',
    transcription: '✗',
    interview_analysis: '✗',
    interview_scoring: '✗',
    combined_score: '✗',
    interview_strengths: '✗',
    critical_red_flags: '✗',
    multi_step: '✗',
    interview_hub: '✗',
    full_transcript: '✗',
    executive_summary: '✗',
    scheduling: '✗',
    natural_language: '✗',
    gcal_sync: 'Partial',
    self_scheduling: '✗',
    availability: '✗',
    double_booking: '✗',
    reschedule: '✗',
    job_posting: '✓',
    ai_job_architect: '✗',
    hiring_policy: '✗',
    job_threshold: '✗',
    job_analytics: 'Basic',
    job_lifecycle: 'Basic',
    offer_generation: '✗',
    live_preview: '✗',
    digital_signing: '✗',
    ai_offer_engine: '✗',
    offer_tracking: '✗',
    onboarding: '✗',
    email_tracker: '✗',
    auto_emails: '✗',
    candidate_notifications: '✗',
    google_meet: '✗',
    candidate_dashboard: '✗',
    career_advisor: '✗',
    app_status: '✗',
    resume_vault: '✗',
    ai_autofill: '✗',
    job_portal: '✓ LinkedIn Jobs',
    job_chat_bot: '✗',
    hiring_dashboard: 'Basic',
    roi_tracking: '✗',
    pipeline_funnel: '✗',
    time_to_hire: 'Basic',
    token_analytics: '✗',
    company_setup: 'Basic',
    timezone_location: '✗',
    team_management: '✓',
    multi_currency: '✗',
    nepal_compliance: '✗',
    white_label: '✗',
    setup_checklist: '✗',
    priority_support: 'Enterprise',
    free_trial: '✗',
    free_plan: '✗',
    pay_per_job: '✗',
    pay_when_hiring: '✗',
    no_annual_contract: '✗',
    no_implementation_fee: '✓',
    no_per_seat: '✗',
    npr_pricing: '✗',
    esewa_khalti: '✗',
    pro_pricing: '$10,000+/yr',
    business_pricing: '$10,000+/yr',
    cost_per_hire: '$10,000+ (annual min)',
    vs_agency_savings: 'More expensive',
  },
  indeed: {
    name: 'Indeed',
    tagline: 'Pay-per-click job board',
    ai_resume_scoring: 'Basic',
    ai_reasoning: '✗',
    ai_job_builder: 'Basic',
    emma_ai: '✗',
    ai_shortlisting: 'Basic',
    bias_detection: '✗',
    ai_salary: 'Salary insights only',
    requirements_gap: '✗',
    red_flags: '✗',
    daily_briefing: '✗',
    candidate_research: 'Resume only',
    ats: 'Basic',
    candidate_profile: 'Resume only',
    stage_tracking: 'Basic',
    bulk_actions: 'Basic',
    score_threshold: '✗',
    candidate_pool: '✓ Large database',
    pool_invites: '✓ Sponsored',
    pool_ai_match: '✗',
    ai_bot: '✗',
    transcription: '✗',
    interview_analysis: '✗',
    interview_scoring: '✗',
    combined_score: '✗',
    interview_strengths: '✗',
    critical_red_flags: '✗',
    multi_step: '✗',
    interview_hub: '✗',
    full_transcript: '✗',
    executive_summary: '✗',
    scheduling: '✗',
    natural_language: '✗',
    gcal_sync: '✗',
    self_scheduling: '✗',
    availability: '✗',
    double_booking: '✗',
    reschedule: '✗',
    job_posting: '✓',
    ai_job_architect: '✗',
    hiring_policy: '✗',
    job_threshold: '✗',
    job_analytics: 'Basic',
    job_lifecycle: 'Basic',
    offer_generation: '✗',
    live_preview: '✗',
    digital_signing: '✗',
    ai_offer_engine: '✗',
    offer_tracking: '✗',
    onboarding: '✗',
    email_tracker: '✗',
    auto_emails: '✗',
    candidate_notifications: 'Basic',
    google_meet: '✗',
    candidate_dashboard: 'Basic',
    career_advisor: '✗',
    app_status: 'Basic',
    resume_vault: '✗',
    ai_autofill: '✗',
    job_portal: '✓ World largest',
    job_chat_bot: '✗',
    hiring_dashboard: 'Basic',
    roi_tracking: '✗',
    pipeline_funnel: '✗',
    time_to_hire: '✗',
    token_analytics: '✗',
    company_setup: 'Basic',
    timezone_location: '✗',
    team_management: 'Basic',
    multi_currency: '✗',
    nepal_compliance: '✗',
    white_label: '✗',
    setup_checklist: '✗',
    priority_support: 'Paid',
    free_trial: '✗',
    free_plan: 'Basic listing',
    pay_per_job: '✓ Pay per click',
    pay_when_hiring: '~ Variable',
    no_annual_contract: '✓',
    no_implementation_fee: '✓',
    no_per_seat: '✓',
    npr_pricing: '✗',
    esewa_khalti: '✗',
    pro_pricing: 'Pay per click',
    business_pricing: 'Pay per click',
    cost_per_hire: 'Variable',
    vs_agency_savings: 'Lower but no workflow',
  },
  greenhouse: {
    name: 'Greenhouse',
    tagline: '$6,500+/yr + $10K setup fee',
    ai_resume_scoring: 'Basic score',
    ai_reasoning: '✗',
    ai_job_builder: 'Templates only',
    emma_ai: '✗',
    ai_shortlisting: 'Basic',
    bias_detection: 'Add-on',
    ai_salary: '✗',
    requirements_gap: '✗',
    red_flags: '✗',
    daily_briefing: '✗',
    candidate_research: 'Resume + LinkedIn',
    ats: '✓ Strong',
    candidate_profile: '✓',
    stage_tracking: '✓',
    bulk_actions: '✓',
    score_threshold: '✗',
    candidate_pool: 'Basic',
    pool_invites: '✗',
    pool_ai_match: '✗',
    ai_bot: '✗',
    transcription: 'Add-on (HireVue)',
    interview_analysis: 'Add-on (HireVue)',
    interview_scoring: 'Add-on',
    combined_score: '✗',
    interview_strengths: '✗',
    critical_red_flags: '✗',
    multi_step: '✓',
    interview_hub: '✓',
    full_transcript: 'Add-on',
    executive_summary: '✗',
    scheduling: '✓',
    natural_language: '✗',
    gcal_sync: '✓',
    self_scheduling: '✓',
    availability: '✓',
    double_booking: '✓',
    reschedule: '✓',
    job_posting: '✓',
    ai_job_architect: '✗',
    hiring_policy: 'Scorecards',
    job_threshold: '✗',
    job_analytics: '✓',
    job_lifecycle: '✓',
    offer_generation: 'Basic templates',
    live_preview: '✗',
    digital_signing: 'Add-on',
    ai_offer_engine: '✗',
    offer_tracking: '✓',
    onboarding: 'Add-on',
    email_tracker: '✓',
    auto_emails: '✓',
    candidate_notifications: '✓',
    google_meet: '✓',
    candidate_dashboard: '✗',
    career_advisor: '✗',
    app_status: 'Basic',
    resume_vault: '✗',
    ai_autofill: '✗',
    job_portal: '✓',
    job_chat_bot: '✗',
    hiring_dashboard: '✓',
    roi_tracking: '✗',
    pipeline_funnel: '✓',
    time_to_hire: '✓',
    token_analytics: '✗',
    company_setup: '✓',
    timezone_location: '✓',
    team_management: '✓',
    multi_currency: 'Enterprise',
    nepal_compliance: '✗',
    white_label: 'Enterprise',
    setup_checklist: '✓',
    priority_support: 'Paid',
    free_trial: '✗',
    free_plan: '✗',
    pay_per_job: '✗',
    pay_when_hiring: '✗',
    no_annual_contract: '✗',
    no_implementation_fee: '✗ $2K-$10K fee',
    no_per_seat: '✗',
    npr_pricing: '✗',
    esewa_khalti: '✗',
    pro_pricing: '$6,500+/yr',
    business_pricing: '$15,000-$70,000/yr',
    cost_per_hire: '$6,500+ (annual min)',
    vs_agency_savings: 'Some savings',
  },
  lever: {
    name: 'Lever',
    tagline: '$6,000+/yr annual contract',
    ai_resume_scoring: 'Basic',
    ai_reasoning: '✗',
    ai_job_builder: 'Templates',
    emma_ai: '✗',
    ai_shortlisting: 'Basic',
    bias_detection: '✗',
    ai_salary: '✗',
    requirements_gap: '✗',
    red_flags: '✗',
    daily_briefing: '✗',
    candidate_research: 'Resume + social',
    ats: '✓',
    candidate_profile: '✓',
    stage_tracking: '✓',
    bulk_actions: '✓',
    score_threshold: '✗',
    candidate_pool: 'CRM sourcing',
    pool_invites: '✓ Outreach',
    pool_ai_match: 'Basic',
    ai_bot: '✗',
    transcription: '✓ Recent addition',
    interview_analysis: 'Basic summaries',
    interview_scoring: 'Basic',
    combined_score: '✗',
    interview_strengths: '✗',
    critical_red_flags: '✗',
    multi_step: '✓',
    interview_hub: '✓',
    full_transcript: '✓',
    executive_summary: 'Basic',
    scheduling: '✓',
    natural_language: '✗',
    gcal_sync: '✓',
    self_scheduling: '✓',
    availability: '✓',
    double_booking: '✓',
    reschedule: '✓',
    job_posting: '✓',
    ai_job_architect: '✗',
    hiring_policy: 'Scorecards',
    job_threshold: '✗',
    job_analytics: '✓',
    job_lifecycle: '✓',
    offer_generation: 'Basic',
    live_preview: '✗',
    digital_signing: 'Add-on',
    ai_offer_engine: '✗',
    offer_tracking: '✓',
    onboarding: '✗',
    email_tracker: '✓',
    auto_emails: '✓',
    candidate_notifications: '✓',
    google_meet: '✓',
    candidate_dashboard: '✗',
    career_advisor: '✗',
    app_status: 'Basic',
    resume_vault: '✗',
    ai_autofill: '✗',
    job_portal: '✓',
    job_chat_bot: '✗',
    hiring_dashboard: '✓',
    roi_tracking: '✗',
    pipeline_funnel: '✓',
    time_to_hire: '✓',
    token_analytics: '✗',
    company_setup: '✓',
    timezone_location: '✓',
    team_management: '✓',
    multi_currency: '✗',
    nepal_compliance: '✗',
    white_label: '✗',
    setup_checklist: '✓',
    priority_support: 'Paid',
    free_trial: '✗',
    free_plan: '✗',
    pay_per_job: '✗',
    pay_when_hiring: '✗',
    no_annual_contract: '✗',
    no_implementation_fee: '✗ $3K-$15K',
    no_per_seat: '✗',
    npr_pricing: '✗',
    esewa_khalti: '✗',
    pro_pricing: '$6,000+/yr',
    business_pricing: '$12,000-$37,000/yr',
    cost_per_hire: '$6,000+ (annual min)',
    vs_agency_savings: 'Some savings',
  },
  workable: {
    name: 'Workable',
    tagline: '$149-599/mo + add-ons',
    ai_resume_scoring: 'Basic AI',
    ai_reasoning: '✗',
    ai_job_builder: '✓ Basic',
    emma_ai: '✗',
    ai_shortlisting: 'Basic',
    bias_detection: '✗',
    ai_salary: '✗',
    requirements_gap: '✗',
    red_flags: '✗',
    daily_briefing: '✗',
    candidate_research: 'Resume only',
    ats: '✓',
    candidate_profile: '✓',
    stage_tracking: '✓',
    bulk_actions: '✓',
    score_threshold: '✗',
    candidate_pool: 'Basic',
    pool_invites: '✓ Basic',
    pool_ai_match: '✗',
    ai_bot: '✗',
    transcription: 'Add-on $99/mo',
    interview_analysis: '✗',
    interview_scoring: '✗',
    combined_score: '✗',
    interview_strengths: '✗',
    critical_red_flags: '✗',
    multi_step: '✓',
    interview_hub: '✓',
    full_transcript: 'Add-on',
    executive_summary: '✗',
    scheduling: '✓',
    natural_language: '✗',
    gcal_sync: '✓',
    self_scheduling: '✓',
    availability: '✓',
    double_booking: '✓',
    reschedule: '✓',
    job_posting: '✓',
    ai_job_architect: 'Basic',
    hiring_policy: 'Basic',
    job_threshold: '✗',
    job_analytics: '✓',
    job_lifecycle: '✓',
    offer_generation: 'Templates',
    live_preview: '✗',
    digital_signing: 'Add-on',
    ai_offer_engine: '✗',
    offer_tracking: '✓',
    onboarding: 'Add-on',
    email_tracker: '✓',
    auto_emails: '✓',
    candidate_notifications: '✓',
    google_meet: 'Add-on',
    candidate_dashboard: '✗',
    career_advisor: '✗',
    app_status: 'Basic',
    resume_vault: '✗',
    ai_autofill: '✗',
    job_portal: '✓',
    job_chat_bot: '✗',
    hiring_dashboard: '✓',
    roi_tracking: '✗',
    pipeline_funnel: '✓',
    time_to_hire: '✓',
    token_analytics: '✗',
    company_setup: '✓',
    timezone_location: '✓',
    team_management: '✓',
    multi_currency: '✗',
    nepal_compliance: '✗',
    white_label: '✗',
    setup_checklist: '✓',
    priority_support: 'Paid',
    free_trial: '✓ 15 days',
    free_plan: '✗',
    pay_per_job: '✗',
    pay_when_hiring: '✗',
    no_annual_contract: '✓',
    no_implementation_fee: '✓',
    no_per_seat: '✗ Per seat',
    npr_pricing: '✗',
    esewa_khalti: '✗',
    pro_pricing: '$149-299/mo base',
    business_pricing: '$477+/mo with add-ons',
    cost_per_hire: '$1,788-5,724/yr',
    vs_agency_savings: 'Some savings',
  },
  ashby: {
    name: 'Ashby',
    tagline: '$400+/mo analytics ATS',
    ai_resume_scoring: '✓ Score only',
    ai_reasoning: '✗',
    ai_job_builder: 'Basic',
    emma_ai: '✗',
    ai_shortlisting: '✓ Basic',
    bias_detection: '✗',
    ai_salary: '✗',
    requirements_gap: '✗',
    red_flags: '✗',
    daily_briefing: '✗',
    candidate_research: 'Resume + LinkedIn',
    ats: '✓ Strong',
    candidate_profile: '✓',
    stage_tracking: '✓',
    bulk_actions: '✓',
    score_threshold: '✗',
    candidate_pool: 'CRM',
    pool_invites: '✓',
    pool_ai_match: '✗',
    ai_bot: '✓ AI Notetaker',
    transcription: '✓',
    interview_analysis: 'Summaries only',
    interview_scoring: '✗',
    combined_score: '✗',
    interview_strengths: '✗',
    critical_red_flags: '✗',
    multi_step: '✓',
    interview_hub: '✓',
    full_transcript: '✓',
    executive_summary: 'Basic',
    scheduling: '✓',
    natural_language: '✗',
    gcal_sync: '✓',
    self_scheduling: '✓',
    availability: '✓',
    double_booking: '✓',
    reschedule: '✓',
    job_posting: '✓',
    ai_job_architect: '✗',
    hiring_policy: 'Scorecards',
    job_threshold: '✗',
    job_analytics: '✓ Strong',
    job_lifecycle: '✓',
    offer_generation: 'Basic',
    live_preview: '✗',
    digital_signing: '✗',
    ai_offer_engine: '✗',
    offer_tracking: '✓',
    onboarding: '✗',
    email_tracker: '✓',
    auto_emails: '✓',
    candidate_notifications: '✓',
    google_meet: '✓',
    candidate_dashboard: '✗',
    career_advisor: '✗',
    app_status: 'Basic',
    resume_vault: '✗',
    ai_autofill: '✗',
    job_portal: '✓',
    job_chat_bot: '✗',
    hiring_dashboard: '✓ Strong analytics',
    roi_tracking: '✗',
    pipeline_funnel: '✓',
    time_to_hire: '✓',
    token_analytics: '✗',
    company_setup: '✓',
    timezone_location: '✓',
    team_management: '✓',
    multi_currency: '✗',
    nepal_compliance: '✗',
    white_label: '✗',
    setup_checklist: '✓',
    priority_support: 'Paid',
    free_trial: '✗',
    free_plan: '✓ Under 10 employees',
    pay_per_job: '✗',
    pay_when_hiring: '✗',
    no_annual_contract: '~ Monthly option',
    no_implementation_fee: '~ Some fees',
    no_per_seat: '✗',
    npr_pricing: '✗',
    esewa_khalti: '✗',
    pro_pricing: '$400+/mo',
    business_pricing: '$8,000-$15,000/yr',
    cost_per_hire: '$4,800+/yr',
    vs_agency_savings: 'Some savings',
  },
  jazzhr: {
    name: 'JazzHR',
    tagline: '$75-420/mo basic ATS',
    ai_resume_scoring: 'Basic keyword',
    ai_reasoning: '✗',
    ai_job_builder: '✗',
    emma_ai: '✗',
    ai_shortlisting: 'Basic',
    bias_detection: '✗',
    ai_salary: '✗',
    requirements_gap: '✗',
    red_flags: '✗',
    daily_briefing: '✗',
    candidate_research: 'Resume only',
    ats: '✓',
    candidate_profile: '✓',
    stage_tracking: '✓',
    bulk_actions: '✓',
    score_threshold: '✗',
    candidate_pool: '✗',
    pool_invites: '✗',
    pool_ai_match: '✗',
    ai_bot: '✗',
    transcription: '✗',
    interview_analysis: '✗',
    interview_scoring: '✗',
    combined_score: '✗',
    interview_strengths: '✗',
    critical_red_flags: '✗',
    multi_step: '✓',
    interview_hub: 'Basic',
    full_transcript: '✗',
    executive_summary: '✗',
    scheduling: 'Basic',
    natural_language: '✗',
    gcal_sync: '✓',
    self_scheduling: 'Basic',
    availability: '✗',
    double_booking: '✗',
    reschedule: '✗',
    job_posting: '✓',
    ai_job_architect: '✗',
    hiring_policy: '✗',
    job_threshold: '✗',
    job_analytics: 'Basic',
    job_lifecycle: '✓',
    offer_generation: 'Templates only',
    live_preview: '✗',
    digital_signing: '✗',
    ai_offer_engine: '✗',
    offer_tracking: 'Basic',
    onboarding: '✗',
    email_tracker: 'Basic',
    auto_emails: 'Basic',
    candidate_notifications: 'Basic',
    google_meet: '✗',
    candidate_dashboard: '✗',
    career_advisor: '✗',
    app_status: '✗',
    resume_vault: '✗',
    ai_autofill: '✗',
    job_portal: '✓',
    job_chat_bot: '✗',
    hiring_dashboard: 'Basic',
    roi_tracking: '✗',
    pipeline_funnel: 'Basic',
    time_to_hire: '✗',
    token_analytics: '✗',
    company_setup: 'Basic',
    timezone_location: '✗',
    team_management: '✓ Unlimited users',
    multi_currency: '✗',
    nepal_compliance: '✗',
    white_label: '✗',
    setup_checklist: '✗',
    priority_support: 'Add-on $119/mo',
    free_trial: '✓ 21 days',
    free_plan: '✗',
    pay_per_job: '✗',
    pay_when_hiring: '✗',
    no_annual_contract: '✓',
    no_implementation_fee: '✓',
    no_per_seat: '✓ Unlimited users',
    npr_pricing: '✗',
    esewa_khalti: '✗',
    pro_pricing: '$75-420/mo',
    business_pricing: '$420/mo max',
    cost_per_hire: '$900-5,040/yr',
    vs_agency_savings: 'Some savings',
  },
  agency: {
    name: 'Recruitment Agency',
    tagline: '15-25% of first year salary',
    ai_resume_scoring: '✗ Human only',
    ai_reasoning: '✗',
    ai_job_builder: '✗',
    emma_ai: '✗',
    ai_shortlisting: '✗ Human only',
    bias_detection: '✗',
    ai_salary: '✗',
    requirements_gap: '✗',
    red_flags: '✗ Sometimes',
    daily_briefing: '✗',
    candidate_research: '✓ Human research',
    ats: '✗',
    candidate_profile: '✓ Human curated',
    stage_tracking: '✗',
    bulk_actions: '✗',
    score_threshold: '✗',
    candidate_pool: '✓ Human network',
    pool_invites: '✓ Human outreach',
    pool_ai_match: '✗',
    ai_bot: '✗',
    transcription: '✗',
    interview_analysis: '✗ Human notes',
    interview_scoring: '✗',
    combined_score: '✗',
    interview_strengths: '✗ Sometimes',
    critical_red_flags: '~ Sometimes',
    multi_step: '✓ Human managed',
    interview_hub: '✗',
    full_transcript: '✗',
    executive_summary: '✓ Human written',
    scheduling: '✓ Human managed',
    natural_language: '✗',
    gcal_sync: '✗',
    self_scheduling: '✗',
    availability: '✗',
    double_booking: '~ Sometimes',
    reschedule: '✓ Human managed',
    job_posting: '✓',
    ai_job_architect: '✗',
    hiring_policy: '~ Brief',
    job_threshold: '✗',
    job_analytics: '✗',
    job_lifecycle: '✗',
    offer_generation: '✓ Human drafted',
    live_preview: '✗',
    digital_signing: '~ Sometimes',
    ai_offer_engine: '✗',
    offer_tracking: '~ Manual',
    onboarding: '✗',
    email_tracker: '✗',
    auto_emails: '✗',
    candidate_notifications: '✓ Human emails',
    google_meet: '✗',
    candidate_dashboard: '✗',
    career_advisor: '~ Sometimes',
    app_status: '✓ Human updates',
    resume_vault: '✗',
    ai_autofill: '✗',
    job_portal: '✗',
    job_chat_bot: '✗',
    hiring_dashboard: '✗',
    roi_tracking: '✗',
    pipeline_funnel: '✗',
    time_to_hire: '✗',
    token_analytics: '✗',
    company_setup: '✗',
    timezone_location: '✗',
    team_management: '✗',
    multi_currency: '✗',
    nepal_compliance: '~ Sometimes',
    white_label: '✗',
    setup_checklist: '✗',
    priority_support: '✓ Dedicated person',
    free_trial: '✗',
    free_plan: '✗',
    pay_per_job: '✓ Per hire',
    pay_when_hiring: '✓ Per hire',
    no_annual_contract: '✓',
    no_implementation_fee: '✓',
    no_per_seat: '✓',
    npr_pricing: '✗',
    esewa_khalti: '✗',
    pro_pricing: '$15,000-25,000/hire',
    business_pricing: '$15,000-25,000/hire',
    cost_per_hire: '$75,000-125,000 (5 hires)',
    vs_agency_savings: 'This IS the agency',
  },
};

export function MasterComparisonTable({ competitorKey }) {
  const competitor = COMPETITOR_DATA[competitorKey];
  if (!competitor) return null;

  let hirenp_wins = 0;
  let competitor_wins = 0;

  HIRENP_FEATURES.forEach(item => {
    if (!item.category) {
      if (item.wins) hirenp_wins++;
      else competitor_wins++;
    }
  });

  return (
    <div style={{ margin: '32px 0', fontFamily: 'system-ui, -apple-system, sans-serif' }}>
      {/* Wins Summary Bar */}
      <div style={{
        display: 'flex',
        gap: '24px',
        background: '#ECFDF5',
        border: '1px solid #A7F3D0',
        borderRadius: '12px',
        padding: '20px 24px',
        marginBottom: '32px',
        flexWrap: 'wrap'
      }}>
        <div style={{ flex: '1', minWidth: '150px' }}>
          <div style={{ fontSize: '36px', fontWeight: 700, color: '#00B67A' }}>{hirenp_wins}</div>
          <div style={{ fontSize: '13px', color: '#065F46', fontWeight: 600 }}>features HireNP wins</div>
        </div>
        <div style={{ flex: '1', minWidth: '150px' }}>
          <div style={{ fontSize: '36px', fontWeight: 700, color: '#374151' }}>{competitor_wins}</div>
          <div style={{ fontSize: '13px', color: '#4B5563', fontWeight: 600 }}>features {competitor.name} wins</div>
        </div>
        <div style={{ flex: '1', minWidth: '150px' }}>
          <div style={{ fontSize: '36px', fontWeight: 700, color: '#F59E0B' }}>15+</div>
          <div style={{ fontSize: '13px', color: '#92400E', fontWeight: 600 }}>features only HireNP has</div>
        </div>
      </div>

      {/* Table */}
      <div style={{ overflowX: 'auto', borderRadius: '12px', border: '1px solid #E5E7EB', boxShadow: '0 4px 24px rgba(0,0,0,0.08)' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', background: 'white', minWidth: '700px' }}>
          <thead>
            <tr>
              <th style={{ padding: '16px', textAlign: 'left', background: '#F9FAFB', borderBottom: '2px solid #E5E7EB', color: '#374151', fontSize: '14px' }}>Feature</th>
              <th style={{ padding: '16px', textAlign: 'center', background: '#00B67A', borderBottom: '2px solid #00B67A', color: 'white' }}>
                <div style={{ fontWeight: 700, fontSize: '16px' }}>HireNP ✦</div>
                <div style={{ fontSize: '11px', fontWeight: 400, opacity: 0.9, marginTop: '4px' }}>From $299/30 days</div>
              </th>
              <th style={{ padding: '16px', textAlign: 'center', background: '#F9FAFB', borderBottom: '2px solid #E5E7EB', color: '#374151' }}>
                <div style={{ fontWeight: 700, fontSize: '16px' }}>{competitor.name}</div>
                <div style={{ fontSize: '11px', fontWeight: 400, opacity: 0.7, marginTop: '4px', color: '#6B7280' }}>{competitor.tagline}</div>
              </th>
            </tr>
          </thead>
          <tbody>
            {HIRENP_FEATURES.map((item, i) => {
              if (item.category) {
                return (
                  <tr key={i}>
                    <td colSpan={3} style={{ background: '#0A0F1E', color: '#00B67A', fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', padding: '8px 16px' }}>
                      {item.category}
                    </td>
                  </tr>
                );
              }

              const compValue = competitor[item.key] || '✗';

              return (
                <tr key={i} style={{ borderBottom: '1px solid #F3F4F6', background: item.wins ? '#F0FDF8' : 'white' }}>
                  <td style={{ padding: '12px 16px' }}>
                    <div style={{ display: 'flex', alignItems: 'center' }}>
                      <span style={{ fontWeight: 600, color: '#374151', fontSize: '14px' }}>{item.feature}</span>
                      {item.unique && (
                        <span style={{ background: '#F59E0B', color: 'white', fontSize: '9px', padding: '2px 6px', borderRadius: '10px', marginLeft: '6px', textTransform: 'uppercase', fontWeight: 700 }}>Only HireNP</span>
                      )}
                    </div>
                    <div style={{ fontSize: '12px', color: '#6B7280', marginTop: '2px' }}>{item.description}</div>
                  </td>
                  
                  <td style={{ padding: '12px 16px', textAlign: 'center', background: item.wins ? '#ECFDF5' : '#F9FAFB', borderLeft: '2px solid #00B67A', borderRight: '2px solid #00B67A' }}>
                    <div style={{ fontWeight: 600, color: '#065F46', fontSize: '13px' }}>
                      {item.hirenp}
                      {item.wins && (
                        <span style={{ background: '#00B67A', color: 'white', fontSize: '9px', padding: '2px 6px', borderRadius: '10px', marginLeft: '6px', fontWeight: 700 }}>wins</span>
                      )}
                    </div>
                    {item.hirenp_note && (
                      <div style={{ fontSize: '11px', color: '#6B7280', fontWeight: 400, marginTop: '4px', fontStyle: 'italic' }}>{item.hirenp_note}</div>
                    )}
                  </td>
                  
                  <td style={{ padding: '12px 16px', textAlign: 'center', color: compValue === '✗' ? '#9CA3AF' : '#4B5563', fontSize: '13px' }}>
                    {compValue}
                  </td>
                </tr>
              );
            })}
          </tbody>
          <tfoot>
            <tr>
              <td colSpan={3} style={{ background: '#00B67A', textAlign: 'center', padding: '20px' }}>
                <a href="https://app.hire-np.com/auth/login" style={{ background: 'white', color: '#00B67A', fontWeight: 700, padding: '12px 32px', borderRadius: '24px', textDecoration: 'none', display: 'inline-block', fontSize: '14px' }}>
                  Try HireNP Free for 15 Days — No Card Required →
                </a>
              </td>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  );
}
